@baseUrl = http://localhost:5000

### POST ###
POST {{baseUrl}}/movies HTTP/1.1
content-type: application/json

{
    "name": "B16",
    "sinopse": "Lorem Ipsum XXXX Marlon",
    "rating": "10", 
    "url_image": "http://aaaaaaa.com.br",
    "cast": ["João Paulo", "Igor Motta", "Samuel", "Natalie Guimaraes"]
}

### USER RANKING  ###
GET {{baseUrl}}/movies HTTP/1.1
###
GET {{baseUrl}}/movies?title=B16 HTTP/1.1
###
GET {{baseUrl}}/movies?actor=Igor HTTP/1.1
###
GET {{baseUrl}}/movies/1648162481445 HTTP/1.1
###
PUT {{baseUrl}}/movies/1648162481445 HTTP/1.1
content-type: application/json

{
    "name": "B17",
    "sinopse": "Lorem Ipsum",
    "rating": "10", 
    "url_image": "http://aaaaaaa.com.br"
}

###

DELETE {{baseUrl}}/movies/1648149149506 HTTP/1.1

